### PR TITLE
style: GEOT-95: post single component styleguide

### PR DESCRIPTION
**Pull request by ra8ga**

### CODE REVIEW

**Comment by ra8ga** [comment]
retest this please

**Comment by ra8ga** [comment]
retest this please

**Comment by ra8ga** [comment]
retest this please

**Comment by ra8ga** [comment]
> again, css is broken, have you checked? no

text is black - should be white, in the project that styling comes from global css - please decide if we should rely on global styles (like body {}) or I should apply explicit styling inside every component. 

Please be aware that there are missing other styles (like proper font-face, sizes.

Also what I should do if some component has no background (so it takes background color of if's parent (black, or gray), but text is white - it looks ok in the project but inside styleguideist there will be white text on white background (as styleguide background is white).
Should I create custom styles inside styleguidist to make it look ok?

**Comment by mariusz-kabala** [comment]
part 1
in general you should avoid global as much as possible - and it was your decision to introduce it. I was always against. But if we have them, than you need to load all globals into styleguide, so components can look like on page - which most probably will need up with extra work for me - as  we will need a separate styleguide per monorepo app because we have those globals. Again - shitty solution which makes other things harder.
part 2
if something does not make sense to display alone - wrap it with something else in styleguide so it can look good.

**Comment by ra8ga** [comment]
> even with global css loaded singlePost is still broken.

fixed

**Pull request merged**
